------ 샘플 데이터 추가 ------------------------------------------------------------------------------------------------------------------------

/* 1. 관리자 회원 */
INSERT INTO STUDY_MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NICKNAME, MEMBER_ROLE)
VALUES (SEQ_MEMBER_NO.NEXTVAL, 'admin', '1234', '관리자', 'ADMIN');


/* 2. 단어 샘플: 話す */
INSERT INTO WORD (WORD_NO, WORD_TEXT, FURIGANA, PART_OF_SPEECH, JLPT_LEVEL, WORD_DESCRIPTION)
VALUES (SEQ_WORD_NO.NEXTVAL, '話す', 'はなす', '동사', 'N5', '기본적인 말하기 동사');

INSERT INTO WORD_MEANING (MEANING_NO, WORD_NO, MEANING_TEXT, MEANING_ORDER, DESCRIPTION)
VALUES (SEQ_WORD_MEANING_NO.NEXTVAL, (SELECT WORD_NO FROM WORD WHERE WORD_TEXT = '話す'), '말하다', 1, '사람과 말이나 이야기를 주고받는 느낌. 단순히 소리를 내는 것보다 의사소통의 의미가 강함.');

INSERT INTO WORD_ACCEPTED_ANSWER (ANSWER_NO, MEANING_NO, ANSWER_TEXT, ANSWER_TYPE)
VALUES (SEQ_WORD_ANSWER_NO.NEXTVAL, (SELECT MEANING_NO FROM WORD_MEANING WHERE WORD_NO = (SELECT WORD_NO FROM WORD WHERE WORD_TEXT = '話す') AND MEANING_TEXT = '말하다'), '말하다', 'MAIN');

INSERT INTO WORD_ACCEPTED_ANSWER (ANSWER_NO, MEANING_NO, ANSWER_TEXT, ANSWER_TYPE)
VALUES (SEQ_WORD_ANSWER_NO.NEXTVAL, (SELECT MEANING_NO FROM WORD_MEANING WHERE WORD_NO = (SELECT WORD_NO FROM WORD WHERE WORD_TEXT = '話す') AND MEANING_TEXT = '말하다'), '이야기하다', 'ACCEPTED');

INSERT INTO WORD_ACCEPTED_ANSWER (ANSWER_NO, MEANING_NO, ANSWER_TEXT, ANSWER_TYPE)
VALUES (SEQ_WORD_ANSWER_NO.NEXTVAL, (SELECT MEANING_NO FROM WORD_MEANING WHERE WORD_NO = (SELECT WORD_NO FROM WORD WHERE WORD_TEXT = '話す') AND MEANING_TEXT = '말하다'), '대화하다', 'ACCEPTED');

INSERT INTO WORD_EXAMPLE (EXAMPLE_NO, WORD_NO, EXAMPLE_TEXT, EXAMPLE_READING, EXAMPLE_MEANING, EXAMPLE_ORDER)
VALUES (SEQ_WORD_EXAMPLE_NO.NEXTVAL, (SELECT WORD_NO FROM WORD WHERE WORD_TEXT = '話す'), '友達と話す', 'ともだちとはなす', '친구와 이야기하다', 1);


/* 3. 한자 샘플: 水 */
INSERT INTO KANJI (KANJI_NO, KANJI_TEXT, ON_READING, KUN_READING, MEANING_TEXT, JLPT_LEVEL, DESCRIPTION)
VALUES (SEQ_KANJI_NO.NEXTVAL, '水', 'スイ', 'みず', '물', 'N5', '물, 액체, 수분과 관련된 의미를 가진 기본 한자');

INSERT INTO KANJI_ACCEPTED_ANSWER (ANSWER_NO, KANJI_NO, ANSWER_TEXT, ANSWER_TYPE)
VALUES (SEQ_KANJI_ANSWER_NO.NEXTVAL, (SELECT KANJI_NO FROM KANJI WHERE KANJI_TEXT = '水'), '물', 'MAIN');

INSERT INTO KANJI_ACCEPTED_ANSWER (ANSWER_NO, KANJI_NO, ANSWER_TEXT, ANSWER_TYPE)
VALUES (SEQ_KANJI_ANSWER_NO.NEXTVAL, (SELECT KANJI_NO FROM KANJI WHERE KANJI_TEXT = '水'), '수', 'ACCEPTED');

INSERT INTO KANJI_EXAMPLE (EXAMPLE_NO, KANJI_NO, EXAMPLE_TEXT, EXAMPLE_READING, EXAMPLE_MEANING, EXAMPLE_ORDER)
VALUES (SEQ_KANJI_EXAMPLE_NO.NEXTVAL, (SELECT KANJI_NO FROM KANJI WHERE KANJI_TEXT = '水'), '水曜日', 'すいようび', '수요일', 1);

INSERT INTO KANJI_EXAMPLE (EXAMPLE_NO, KANJI_NO, EXAMPLE_TEXT, EXAMPLE_READING, EXAMPLE_MEANING, EXAMPLE_ORDER)
VALUES (SEQ_KANJI_EXAMPLE_NO.NEXTVAL, (SELECT KANJI_NO FROM KANJI WHERE KANJI_TEXT = '水'), '水道', 'すいどう', '수도', 2);


/* 4. 가나 샘플 */
INSERT INTO KANA (KANA_NO, HIRAGANA, KATAKANA, ROMAJI, KOREAN_SOUND, KANA_ROW, KANA_COLUMN, KANA_ORDER)
VALUES (SEQ_KANA_NO.NEXTVAL, 'あ', 'ア', 'a', '아', 'あ행', 'あ단', 1);

INSERT INTO KANA (KANA_NO, HIRAGANA, KATAKANA, ROMAJI, KOREAN_SOUND, KANA_ROW, KANA_COLUMN, KANA_ORDER)
VALUES (SEQ_KANA_NO.NEXTVAL, 'い', 'イ', 'i', '이', 'あ행', 'い단', 2);

COMMIT;