
/* システムの全体的な仕組み

STUDY_MEMBER

WORD
WORD_MEANING
WORD_ACCEPTED_ANSWER
WORD_EXAMPLE

KANJI
KANJI_ACCEPTED_ANSWER
KANJI_EXAMPLE

KANA

*/

/* =========================================================
   1. STUDY_MEMBER
   회원 정보
   ========================================================= */

CREATE TABLE STUDY_MEMBER (
    MEMBER_NO NUMBER PRIMARY KEY,
    MEMBER_ID VARCHAR2(50 CHAR) NOT NULL UNIQUE,
    MEMBER_PW VARCHAR2(100 CHAR) NOT NULL,
    MEMBER_NICKNAME VARCHAR2(50 CHAR) NOT NULL,
    MEMBER_ROLE VARCHAR2(20 CHAR) DEFAULT 'USER' NOT NULL,
    ENROLL_DATE DATE DEFAULT SYSDATE NOT NULL,
    DELETE_FL CHAR(1 CHAR) DEFAULT 'N' NOT NULL,

    CONSTRAINT CHK_STUDY_MEMBER_ROLE
        CHECK (MEMBER_ROLE IN ('USER', 'ADMIN')),

    CONSTRAINT CHK_STUDY_MEMBER_DELETE_FL
        CHECK (DELETE_FL IN ('Y', 'N'))
);

CREATE SEQUENCE SEQ_MEMBER_NO START WITH 1 INCREMENT BY 1 NOCACHE;


/* =========================================================
   2. WORD
   단어 / 표현 기본 정보
   예: 話す, 約束, しかし
   ========================================================= */

CREATE TABLE WORD (
    WORD_NO NUMBER PRIMARY KEY,
    WORD_TEXT VARCHAR2(100 CHAR) NOT NULL,
    FURIGANA VARCHAR2(100 CHAR),
    PART_OF_SPEECH VARCHAR2(30 CHAR) NOT NULL,
    JLPT_LEVEL VARCHAR2(10 CHAR) DEFAULT 'NONE' NOT NULL,
    WORD_DESCRIPTION VARCHAR2(500 CHAR),
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT DATE,
    DELETE_FL CHAR(1 CHAR) DEFAULT 'N' NOT NULL,

    CONSTRAINT CHK_WORD_PART_OF_SPEECH
        CHECK (PART_OF_SPEECH IN ('명사', '동사', '형용사', '부사·접속사', '표현', '기타')),

    CONSTRAINT CHK_WORD_JLPT
        CHECK (JLPT_LEVEL IN ('N5', 'N4', 'N3', 'N2', 'N1', 'NONE')),

    CONSTRAINT CHK_WORD_DELETE_FL
        CHECK (DELETE_FL IN ('Y', 'N'))
);

CREATE SEQUENCE SEQ_WORD_NO START WITH 1 INCREMENT BY 1 NOCACHE;


/* =========================================================
   3. WORD_MEANING
   단어 뜻
   하나의 단어가 여러 뜻을 가질 수 있음
   DESCRIPTION은 뜻 상세 설명, 최대 500자
   ========================================================= */

CREATE TABLE WORD_MEANING (
    MEANING_NO NUMBER PRIMARY KEY,
    WORD_NO NUMBER NOT NULL,
    MEANING_TEXT VARCHAR2(200 CHAR) NOT NULL,
    MEANING_ORDER NUMBER DEFAULT 1 NOT NULL,
    DESCRIPTION VARCHAR2(500 CHAR),
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT DATE,
    DELETE_FL CHAR(1 CHAR) DEFAULT 'N' NOT NULL,

    CONSTRAINT FK_WORD_MEANING_WORD
        FOREIGN KEY (WORD_NO) REFERENCES WORD(WORD_NO),

    CONSTRAINT UQ_WORD_MEANING_ORDER
        UNIQUE (WORD_NO, MEANING_ORDER),

    CONSTRAINT CHK_WORD_MEANING_DELETE_FL
        CHECK (DELETE_FL IN ('Y', 'N'))
);

CREATE SEQUENCE SEQ_WORD_MEANING_NO START WITH 1 INCREMENT BY 1 NOCACHE;


/* =========================================================
   4. WORD_ACCEPTED_ANSWER
   단어 뜻별 허용 정답
   MAIN / ACCEPTED만 사용
   ========================================================= */

CREATE TABLE WORD_ACCEPTED_ANSWER (
    ANSWER_NO NUMBER PRIMARY KEY,
    MEANING_NO NUMBER NOT NULL,
    ANSWER_TEXT VARCHAR2(200 CHAR) NOT NULL,
    ANSWER_TYPE VARCHAR2(20 CHAR) NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    DELETE_FL CHAR(1 CHAR) DEFAULT 'N' NOT NULL,

    CONSTRAINT FK_WORD_ANSWER_MEANING
        FOREIGN KEY (MEANING_NO) REFERENCES WORD_MEANING(MEANING_NO),

    CONSTRAINT CHK_WORD_ANSWER_TYPE
        CHECK (ANSWER_TYPE IN ('MAIN', 'ACCEPTED')),

    CONSTRAINT CHK_WORD_ANSWER_DELETE_FL
        CHECK (DELETE_FL IN ('Y', 'N')),

    CONSTRAINT UQ_WORD_MEANING_ANSWER
        UNIQUE (MEANING_NO, ANSWER_TEXT)
);

CREATE SEQUENCE SEQ_WORD_ANSWER_NO START WITH 1 INCREMENT BY 1 NOCACHE;


/* =========================================================
   5. WORD_EXAMPLE
   단어 예문
   ========================================================= */

CREATE TABLE WORD_EXAMPLE (
    EXAMPLE_NO NUMBER PRIMARY KEY,
    WORD_NO NUMBER NOT NULL,
    EXAMPLE_TEXT VARCHAR2(300 CHAR) NOT NULL,
    EXAMPLE_READING VARCHAR2(300 CHAR),
    EXAMPLE_MEANING VARCHAR2(300 CHAR),
    EXAMPLE_ORDER NUMBER DEFAULT 1 NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT DATE,
    DELETE_FL CHAR(1 CHAR) DEFAULT 'N' NOT NULL,

    CONSTRAINT FK_WORD_EXAMPLE_WORD
        FOREIGN KEY (WORD_NO) REFERENCES WORD(WORD_NO),

    CONSTRAINT UQ_WORD_EXAMPLE_ORDER
        UNIQUE (WORD_NO, EXAMPLE_ORDER),

    CONSTRAINT CHK_WORD_EXAMPLE_DELETE_FL
        CHECK (DELETE_FL IN ('Y', 'N'))
);

CREATE SEQUENCE SEQ_WORD_EXAMPLE_NO START WITH 1 INCREMENT BY 1 NOCACHE;


/* =========================================================
   6. KANJI
   단일 한자 정보
   예: 水, 火, 人
   ========================================================= */

CREATE TABLE KANJI (
    KANJI_NO NUMBER PRIMARY KEY,
    KANJI_TEXT VARCHAR2(10 CHAR) NOT NULL UNIQUE,
    ON_READING VARCHAR2(100 CHAR),
    KUN_READING VARCHAR2(100 CHAR),
    MEANING_TEXT VARCHAR2(200 CHAR) NOT NULL,
    JLPT_LEVEL VARCHAR2(10 CHAR) DEFAULT 'NONE' NOT NULL,
    DESCRIPTION VARCHAR2(500 CHAR),
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT DATE,
    DELETE_FL CHAR(1 CHAR) DEFAULT 'N' NOT NULL,

    CONSTRAINT CHK_KANJI_JLPT
        CHECK (JLPT_LEVEL IN ('N5', 'N4', 'N3', 'N2', 'N1', 'NONE')),

    CONSTRAINT CHK_KANJI_DELETE_FL
        CHECK (DELETE_FL IN ('Y', 'N'))
);

CREATE SEQUENCE SEQ_KANJI_NO START WITH 1 INCREMENT BY 1 NOCACHE;


/* =========================================================
   7. KANJI_ACCEPTED_ANSWER
   한자 뜻 허용 정답
   예: 水 → 물, 수
   ========================================================= */

CREATE TABLE KANJI_ACCEPTED_ANSWER (
    ANSWER_NO NUMBER PRIMARY KEY,
    KANJI_NO NUMBER NOT NULL,
    ANSWER_TEXT VARCHAR2(200 CHAR) NOT NULL,
    ANSWER_TYPE VARCHAR2(20 CHAR) NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    DELETE_FL CHAR(1 CHAR) DEFAULT 'N' NOT NULL,

    CONSTRAINT FK_KANJI_ANSWER_KANJI
        FOREIGN KEY (KANJI_NO) REFERENCES KANJI(KANJI_NO),

    CONSTRAINT CHK_KANJI_ANSWER_TYPE
        CHECK (ANSWER_TYPE IN ('MAIN', 'ACCEPTED')),

    CONSTRAINT CHK_KANJI_ANSWER_DELETE_FL
        CHECK (DELETE_FL IN ('Y', 'N')),

    CONSTRAINT UQ_KANJI_ANSWER
        UNIQUE (KANJI_NO, ANSWER_TEXT)
);

CREATE SEQUENCE SEQ_KANJI_ANSWER_NO START WITH 1 INCREMENT BY 1 NOCACHE;


/* =========================================================
   8. KANJI_EXAMPLE
   한자 용례
   예: 水曜日, 水道, 水分
   ========================================================= */

CREATE TABLE KANJI_EXAMPLE (
    EXAMPLE_NO NUMBER PRIMARY KEY,
    KANJI_NO NUMBER NOT NULL,
    EXAMPLE_TEXT VARCHAR2(300 CHAR) NOT NULL,
    EXAMPLE_READING VARCHAR2(300 CHAR),
    EXAMPLE_MEANING VARCHAR2(300 CHAR),
    EXAMPLE_ORDER NUMBER DEFAULT 1 NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT DATE,
    DELETE_FL CHAR(1 CHAR) DEFAULT 'N' NOT NULL,

    CONSTRAINT FK_KANJI_EXAMPLE_KANJI
        FOREIGN KEY (KANJI_NO) REFERENCES KANJI(KANJI_NO),

    CONSTRAINT UQ_KANJI_EXAMPLE_ORDER
        UNIQUE (KANJI_NO, EXAMPLE_ORDER),

    CONSTRAINT CHK_KANJI_EXAMPLE_DELETE_FL
        CHECK (DELETE_FL IN ('Y', 'N'))
);

CREATE SEQUENCE SEQ_KANJI_EXAMPLE_NO START WITH 1 INCREMENT BY 1 NOCACHE;


/* =========================================================
   9. KANA
   히라가나 / 가타카나 고정표
   ========================================================= */

CREATE TABLE KANA (
    KANA_NO NUMBER PRIMARY KEY,
    HIRAGANA VARCHAR2(10 CHAR) NOT NULL,
    KATAKANA VARCHAR2(10 CHAR) NOT NULL,
    ROMAJI VARCHAR2(20 CHAR) NOT NULL,
    KOREAN_SOUND VARCHAR2(20 CHAR),
    KANA_ROW VARCHAR2(20 CHAR),
    KANA_COLUMN VARCHAR2(20 CHAR),
    KANA_ORDER NUMBER NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,

    CONSTRAINT UQ_KANA_HIRAGANA
        UNIQUE (HIRAGANA),

    CONSTRAINT UQ_KANA_KATAKANA
        UNIQUE (KATAKANA),

    CONSTRAINT UQ_KANA_ORDER
        UNIQUE (KANA_ORDER)
);

CREATE SEQUENCE SEQ_KANA_NO START WITH 1 INCREMENT BY 1 NOCACHE;